version: "3.4"

services:
  redis:
    image: redis:7
    restart: always
    hostname: redis
    networks:
      - booking-backend-app
    volumes:
      - booking-redis:/data
    ports:
      - '6379:6379'

  postgres:
    hostname: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./src/main/resources/db/booking.sql:/docker-entrypoint-initdb.d/booking.sql
    ports:
      - "5432:5432"
    networks:
      - booking-backend-app
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.23
    ports:
      - 9200:9200
      - 9300:9300
    restart: always
    hostname: elasticsearch
    networks:
      - booking-backend-app
    volumes:
      - booking-es:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    hostname: rabbitmq
    networks:
      - booking-backend-app

  booking-backend:
    image: nhathoang07/booking-backend:v1
    environment:
      - DB_URL=postgres
      - DB_PORT=5432
      - DB_NAME=booking_db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_PORT=15672
      - MAIL_USERNAME=nhathv@beetsoft.com.vn
      - MAIL_PASSWORD=xnhtcgjdtmstjiwl
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
      - ES_URL=elasticsearch:9200
      - ES_USERNAME=admin
      - ES_PASSWORD=admin
      - ES_INDEX=booking
      - ACCESS_KEY=AKIAZXLNCWVCFMS7WTWR
      - SECRET_KEY=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
      - BUCKET_NAME=booking-backend
    ports:
      - "8181:8080"
    depends_on:
      - postgres
      - redis
      - rabbitmq
      - elasticsearch
    networks:
      - booking-backend-app

volumes:
  booking-redis:
    driver: local
  booking-es:
    driver: local
  postgres:
    driver: local

networks:
  booking-backend-app:
    driver: bridge
